import { Global, Module } from '@nestjs/common';
import {
  CareersController,
  CataloguesController,
  CurriculaController,
  InformationStudentsController,
  InstitutionsController,
  StudentsController,
  SubjectsController,
  InformationTeachersController,
  //Nuestros Controladores
  CandidatosController,
  CargosController,
  CarrerasController,
  CronogramasController,
  EstadosController,
  ListasController,
  PeriodosLectivosController,
  RolesController,
  TareasController,
  TiposListasController,
  UsuariosController,
  VotosController
} from '@core/controllers';
import {
  CareersService,
  CataloguesService,
  CurriculaService,
  InformationStudentsService,
  InstitutionsService,
  StudentsService,
  SubjectsService,
  InformationTeachersService,
  CandidatosService,
  CargosService,
  CarrerasService,
  CronogramasService,
  EstadosService,
  ListasService,
  PeriodosLectivosService,
  RolesService,
  TareasService,
  TiposListasService,
  UsuariosService,
  VotosService,
} from '@core/services';
import { DatabaseModule } from '@database';
import { coreProviders } from '@core/providers';

@Global()
@Module({
  imports: [DatabaseModule],
  controllers: [
    CareersController,
    CataloguesController,
    CurriculaController,
    InformationStudentsController,
    InformationTeachersController,
    InstitutionsController,
    StudentsController,
    SubjectsController,

    //Nuestros Controladores
    CandidatosController,
    CargosController,
    CarrerasController,
    CronogramasController,
    EstadosController,
    ListasController,
    PeriodosLectivosController,
    RolesController,
    TareasController,
    TiposListasController,
    UsuariosController,
    VotosController
  ],
  providers: [
    ...coreProviders,
    CareersService,
    CataloguesService,
    CurriculaService,
    InformationStudentsService,
    InformationTeachersService,
    InstitutionsService,
    StudentsService,
    SubjectsService,

    //Nuestros Proveedores
    CandidatosService,
    CargosService,
    CarrerasService,
    CronogramasService,
    EstadosService,
    ListasService,
    PeriodosLectivosService,
    RolesService,
    TareasService,
    TiposListasService,
    UsuariosService,
    VotosService,
  ],
  exports: [
    ...coreProviders,
    CareersService,
    CataloguesService,
    CurriculaService,
    InformationStudentsService,
    InformationTeachersService,
    InstitutionsService,
    StudentsService,
    SubjectsService,

    //Nuestros Exports
    CandidatosService,
    CargosService,
    CarrerasService,
    CronogramasService,
    EstadosService,
    ListasService,
    PeriodosLectivosService,
    RolesService,
    TareasService,
    TiposListasService,
    UsuariosService,
    VotosService,
  ],
})
export class CoreModule {}
